[pytest]
# Indica onde o pytest deve procurar testes
testpaths = tests

# Evita que o pytest entre em pastas indesejadas
norecursedirs = .venv .git venv build dist Program Files AppData

# Filtra os nomes de arquivos de teste
python_files = test_*.py